# Generated by Django 4.2.20 on 2025-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
    ]
