# Generated by Django 4.2.20 on 2025-05-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_cbe_account_number_userprofile_email_and_more'),
    ]

    operations = [
    ]
