# Generated by Django 4.2.20 on 2025-05-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equbmember',
            name='created_at',
        ),
        migrations.AddField(
            model_name='equbmember',
            name='assigned_members_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equbmember',
            name='total_paid_to_upline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='equbmember',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='queue_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='upline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equb.equbmember'),
        ),
    ]
