# Generated by Django 4.2.20 on 2025-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equb', '0003_remove_equbmember_assigned_members_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equbmember',
            name='initial_payment_made',
            field=models.BooleanField(default=False),
        ),
    ]
