# Generated by Django 4.2.20 on 2025-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equb', '0004_equbmember_initial_payment_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equbmember',
            name='initial_payment_made',
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='queue_position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='total_paid_to_upline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='equbmember',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
